---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    dolittle.io/tenant-id: {{tenantId}}
    dolittle.io/application-id: {{applicationId}}
    dolittle.io/microservice-id: {{id}}
  labels:
    tenant: {{tenant}}
    application: {{pascalCase applicationName}}
    environment: Dev
    microservice: {{pascalCase name}}
  name:  dev-{{lowerCase name}}-secret-env-variables
  namespace: application-{{applicationId}}
type: Opaque
data:

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    dolittle.io/tenant-id: {{tenantId}}
    dolittle.io/application-id: {{applicationId}}
    dolittle.io/microservice-id: {{id}}
  labels:
    tenant: {{tenant}}
    application: {{pascalCase applicationName}}
    environment: Dev
    microservice: {{pascalCase name}}
  name: dev-{{lowerCase name}}-env-variables
  namespace: application-{{applicationId}}
data:
  DATABASE__HOST: "dev-mongo.application-{{applicationId}}.svc.cluster.local"
  DATABASE__NAME: "read_models_{{lowerCase name}}"
  DOLITTLE__RUNTIME__HHOST: "localhost"
  DOLITTLE__RUNTIME__HPORT: "50053"
  EVENTSTORE__HOST: "dev-mongo.application-{{applicationId}}.svc.cluster.local"
  EVENTSTORE__NAME: "event_store_{{lowerCase name}}"
  NODE_ENV: "production"
  PORT: "80"

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    dolittle.io/tenant-id: {{tenantId}}
    dolittle.io/application-id: {{applicationId}}
    dolittle.io/microservice-id: {{id}}
  labels:
    tenant: {{tenant}}
    application: {{pascalCase applicationName}}
    environment: Dev
    microservice: {{pascalCase name}}
  name: dev-{{lowerCase name}}-config-files
  namespace: application-{{applicationId}}
data:

