name: Build

on:
  push:
    branches:
      - "**"
    paths:
      - "Source/**"

jobs:
  build-node:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          yarn ci


  build-dotnet:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.102'
      - name: Build .NET
        run: dotnet build --configuration Release
      - name: Test .NET
        run: dotnet test --configuration Release --no-build
