name: Publish

env:
  PRERELEASE_BRANCHES: "" # Comma separated list of prerelease branch names. 'alpha,rc, ...'

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - name: Build Node packages
        run: |
          yarn
          yarn ci

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.102'
      - name: Build .NET
        run: dotnet build --configuration Release
      - name: Test .NET
        run: dotnet test --configuration Release --no-build

      - name: Establish context
        id: context
        uses: dolittle/establish-context-action@v2 # Replace with ./ if used withing dolittle/establish-context-action
        with:
          prerelease-branches: ${{ env.PRERELEASE_BRANCHES }}

      - name: Increment version
        id: increment-version
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        uses: dolittle/increment-version-action@v2
        with:
          version: ${{ steps.context.outputs.current-version }}
          release-type: ${{ steps.context.outputs.release-type }}

      - name: Prepend to Changelog
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        uses: dolittle/add-to-changelog-action@v2
        with:
          version: ${{ steps.increment-version.outputs.next-version }}
          body: ${{ steps.context.outputs.pr-body }}
          pr-url: ${{ steps.context.outputs.pr-url }}
          changelog-path: CHANGELOG.md
          user-email: build@dolittle.com
          user-name: dolittle-build

      - name: Create GitHub Release
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        uses: dolittle/github-release-action@v2
        with:
          token: ${{  secrets.BUILD_PAT  }}
          version: ${{ steps.increment-version.outputs.next-version }}
          body: ${{ steps.context.outputs.pr-body }}

      - name: Publish NPM packages
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn publish-version ${{ steps.increment-version.outputs.next-version }}

      - name: Create NuGet packages
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        run: dotnet pack --no-build --configuration Release -o ${{ env.NUGET_OUTPUT }} /p:PackageVersion=${{ steps.increment-version.outputs.next-version }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg


      - name: Push NuGet packages
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        run: dotnet nuget push --skip-duplicate '${{ env.NUGET_OUTPUT }}/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Commit any updated packages
        if: always()
        run: |
          git config "user.email" "build@dolittle.com"
          git config "user.name" "dolittle-build"
          git commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -am "Bumping versions in packages to ${{ steps.context.outputs.current-version }}"
          git push origin main
